### ISSUE TITLE
Issue created

### ISSUE THREAD

**Issue by Kgeovanni** [Kgeovanni/pa_4#1]
Hi Joseph,
Sorry, the "issues" was hidden. I also shared pa_4 as collaborator. 

@jvcasillas

Thank you.
Diana

**Comment by jvcasillas** [comment]
|                 Task                                              | Points | Points earned |
| :---------------------------------------------------------------- | -----: | ------------: |
| Fork the `pa_4` repo                                              |    0.5 | 0.5 |
| Correctly segment items                                           |      2 | 2 |
| Fix scripts and extract data                                      |      2 | 2 |
| Generate a hypothesis                                             |    0.5 | 0.5 |
| Calculate descriptives for VOT, present them in a table           |      1 | 1 |
| Plot VOT                                                          |      1 | 1 |
| Include figure(s) of the acoustic data                            |    0.5 | 0.5 |
| Evaluate your hypothesis                                          |    0.5 | 0 |
| Write a reproducible report                                       |      1 | 1 |
| Knit the reproducible report                                      |      1 | 1 |
| **Total**                                                         |     10 | 9.5 |

Overall, good job. Some comments. First, you knit an html file and also an MD file. The MD file is incomplete, so initially I thought you didn't complete the assignment (take a look at your `README.md` file). However, I downloaded the entire repo and was able to reproduce the HTML file and view it in my browser. Second, you didn't evaluate your hypotheses in any way, so you lost 0.5 points there. I found your reflection at the end interesting, specifically this comment: 

> I had some difficulty looking for the error in the scripts from the pa-4. I was able to resolve all, but the one with the “#” error took long. The next group of students would benefit from knowing the number of errors in each script so they are not overanalyzing (and taking long) each script (like me). For example, I would suggest letting students know that there are 2 errors in scipt_1 and 1 error in script_2 would be helpful.

I agree that this would make the assignment much easier for students, but I believe it kind of misses the point. When you work on any programming task you never know where errors are or how many there are. That is what trouble shooting is all about and that is the skill you should be learning to improve here. Ideally, the process works like this: 1) run the script, 2) get an error, 3) study error message to understand problem, 4) fix problem, 5) start over again at 1) until there are no more errors. It's imperative that you learn this process in order to be successful as a researcher, and my opinion is that I don't do you any favors if I give information about the errors. Anyway, it is an interesting topic and something I am constantly thinking about. I appreciate your feedback.

**Comment by Kgeovanni** [comment]
Hello Joseph, 

Thank you for your comments. In regard to my feedback about script error, I don't think it would be "easier" but I understand that it may appear that way.  This is actually a common thought/concern. The way I think about it is, the content or skill is not being changed, but the presentation of the content is strengthened. The suggestion would be training in a hierarchy order of complexity. For example, in one task students would learn that there are 4 errors in total and they would need to identify/fix them. In the second task, students would not know how many errors there are.  In making my suggestion, I was speaking through my lens as an educator. As a researcher, I have spent numerous hours figuring out codes and learning new tricks. Many times, I had to start over, take breaks and revisit the task at hand. This is an interesting topic. I hope I gave you more content in this message, as my initial feedback may have been insufficient. Thank you for listening.

 I wanted to share with you that I was unable to knit as requested, it prompt me to save it as an html. After a few hours of trying to resolve this issue (doing research online and asking other students) but sadly unsuccesssful. I followed the instructions and knit via html. I will share the code in the next message after I try to run it again. Thank you Joseph I appreciate your feedback and your undivided support.

**Comment by Kgeovanni** [comment]
I attempted to knit it again and it gave me the same output. I am pretty sure I am missing something or I didn't do something. It is always the human and not the machine :) Any suggestions? Thank you Joseph.

output file: [README.knit.md](http://readme.knit.md/)

Error: Functions that produce HTML output found in document targeting gfm-yaml_metadata_block output.
Please change the output type of this document to HTML. Alternatively, you can allow
HTML output in non-HTML formats by adding this option to the YAML front-matter of
your rmarkdown file:

  always_allow_html: true

Note however that the HTML output will not be visible in non-HTML formats.

Execution halted
